/**
	k_amber-reader
    FileReader.h
	FileReader (freader) inherits from FileManipulator. Its main use
		is to read output from AMBER and print results to the screen.
		freader will not generate any files. In the case that FileReader's
		work should be saved, the FileWriter class can be used.

	Notable Bugs:
		10/18/2017: Maybe remove a lot of miscellaneous work from reader into writer, or
		provide better names. As it is now, the only difference between the reader and writer
		is that the reader creates a string and the writer puts it into a file. It adds a lot
		of extra work that is not necessary. This isn't so bad because all the code necessary
		to read and write exists; the problem lies in deciding where that code should go.

    Author(s): Kevin B. Krause
    Version:   unreleased
*/

#pragma once
#include "FileManipulator.h"
#include <vector>
#include <unordered_map>

class FileReader : public FileManipulator
{
public:

	/**
		Constructor for freader objects. Because freader does not
		   have any private data members, it is an empty constructor
		   that also calls the constructor for FileManipulator.
   		Parameters:
      		string filePath - Path to the file being used
   		Returns:
      		An freader object
	*/
	FileReader(string filePath);
	/**
   		Asks the user for n strings and searches for those n strings in a file
   		Parameters:
      		none
   		Returns:
			none
		Bugs:
			This function matches punctuation and case when searching. It should not.
		It should remove all puncutation and change all case to lower case.
	*/
	void count_string();
	/**
   		Hydrogen bond calculation to aggregate average amount of bonds and percentages
			per acceptor/donor pair. The list output by AMBER is not easy to read and must be
			tabulated by hand. Ideally, this function will reduce AMBER's output and provide
			something that can be piped into another program as a substitute for calculating
			everything by hand.
   		Parameters:
      		double threshold_persistence - the percent at which to stop reading the configured file
				A 5% threshold should be passed as 0.05.
   		Returns:
			  A string aggregate of all output ... [ELABORATE]
		Bugs:
			TBD
		Other:
			Alias: hbond_intra_avg.
	*/
	//string hydrogen_bond_intra_average(double threshold_persistence);
	/**
		Determines the distances between two atoms. It is used in conjunction with
			hbond_intra_avg to determine which frames from the simulation can best represent a
			hydrogen bond. The input file is a distance.dat between two atoms.
		Parameters:
			double threshold_persistence - the percent at which to stop reading the configured file
				A 5% threshold should be passed as 0.05.
		Returns:
			none
		Bugs:
			10/23/2017: Returns an empty string with threshold 0 and 100. Fix.
	*/
	void distance_atoms(double threshold_distance);
	/**
		Uses a data file generated by surf and can
			-average the surface area of the analyte
			-provide highest and lowest surface areas, and at which frames
		Parameters:
			none
		Returns:
			String aggregate of all output ... [ELABORATE]
		Bugs:
			Skips the first frame and first surface reading.
			Shows that average is "inf" angstroms.
			Lowest frame is not correct.
		Other:
			I'd like this function to also calculate 68% and 95% confidence values.
	*/
	string surface_average();
	/**
		Configure this object to use a new file for reading. The old one (associated file)
			will be discarded.
		Parameters:
			string newPath - Path to the new file being read
		Returns:
			true - Old file closed and newPath set
			false - Either: newPath does not exist, OR old file is still open/cannot be closed
		Other:
			Can we report how it failed (stderr) and why it returns false?
	*/
	bool set_file_path(string newPath) override;
	/**
		"Fix" a PDB file by changing the following:
			-change all instances of "INT" to the monomer's 3 letter acronym
			-remove all lines starting with "CONECT"
			-remove all lines starting with "LINK"
			-add a "TER" and "END" to the end of the file
		Parameters:
			string monomer - the 3 letter acronyom of the monomer on the micelle, such as
				poly(SULL) being ULL, poly(SULV) being ULV, and so on
		Returns:
			none
		Bugs:
			Commented out a file handle, needs to return a string.
	*/
	string autofix_pdb(string monomer);

	virtual string analyze(double threshold);
	virtual string analyze(string s);
	virtual string analyze();

protected:

	inline void pre_read_greeting(string title, string msg);

	// override for FileManipulator::open_file
	void open_file() override;
	// override for FileManipulator::close_file
	void close_file() override;

private:

	inline void invalid_analysis();

};