/**
	k_amber-reader
	SASAReader.h
		The SASAReader class analyzes .dat files generated from the surf command, which is
		used in conjunction with cpptraj.

	Author(s): Kevin B. Krause
	Version:   unreleased
*/

#pragma once
#include "FileReader.h"

class SASAReader : public FileReader
{
public:

	SASAReader(string filePath);
	/**
		Uses a data file generated by surf and can
			-average the surface area of the analyte
			-provide highest and lowest surface areas, and at which frames
		Parameters:
			none
		Returns:
			String aggregate of all output ... [ELABORATE]
		Bugs:
			Skips the first frame and first surface reading.
			Shows that average is "inf" angstroms.
			Lowest frame is not correct.
		Other:
			I'd like this function to also calculate 68% and 95% confidence values.
	*/
	string analyze() override;
};